@startuml
rectangle Roles{
    class Utilisateur{
        id : int
        nom : string
        role[] : array
    }
    class Visiteur{}
    class Redacteur{}
    class Administrateur{}
}

class Abonnement{
    id : int
    titre : string
    prix : float
    image : string
}
class Newsletter{
}
class Demande{
    id : int
    objet : string
    texte : text
}

Utilisateur -|> Visiteur
Redacteur -|> Utilisateur
Administrateur -|> Redacteur

Administrateur -- Abonnement : administrer
Administrateur -- Demande : voir
Administrateur -- Utilisateur : envoyer

Utilisateur -- Newsletter : inscrire

Visiteur -- Demande : faire
Visiteur -- Abonnement : voir



@enduml