@startuml


rectangle ROLE{
    Visiteur as V
    Redacteur as R
    Administrateur as A
}



R-|>V
A-|>R


rectangle UserStory-Sprint1{
    V-->(Je peux naviguer sur le site vitrine)
    R-->(Je peux changer la page d'acceuil du site)
    R-->(Je peux administrer les rubriques menu)
    A-->(Je peux administrer les rédacteurs)
}

@enduml